# Generated by Django 5.2.4 on 2025-08-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placement_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
